### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by FZambia** [synw/centcli#1]
Hello, thanks for an interesting tool!

First about config. Do you think that current format is handy, for me it would be much simpler to see sth like:

```json
{
	"nodes": [
		{
			"name": "local",
			"host":"localhost",
			"port":8001,
			"secret":"secret_key"
		},
		{
			"name": "local2",
			"host":"localhost",
			"port":8002,
			"secret":"secret_key"
		}
	]
}
```

I.e. a bit shorter and using Centrifugo terminology?

[This parsing](https://github.com/synw/centcli/blob/master/libcentcli/conf/conf.go#L28) is a bit more complex then needed - you can look how we parse [namespaces key in Centrifugo](https://github.com/centrifugal/centrifugo/blob/master/libcentrifugo/node/config.go#L285).

Also I noticed that when listening channel you use user with ID `cli` - so in this moment that user will be a general user in channel and calling presence will return it in response. Unfortunately I don't know a better way - there is no concept of system users in Centrifugo...

When showing stats you could sort them alphabetically.

Also as our `go` client can change soon - you better to vendor dependencies, as `centcli` is an executable it's a convenient practice for Go.

**Comment by FZambia** [comment]
Thinking more, actually I'd prefer even less typing for config:

```json
{
	"nodes": [
		{
			"name": "local",
			"addr":"localhost:8001",
			"secret":"secret_key"
		},
		{
			"name": "local2",
			"addr":"localhost:8002",
			"secret":"secret_key"
		}
	]
}
```

Also will client detect address scheme automatically? I.e. will it work with TLS node?

Also noticed [a line](https://github.com/synw/centcli/blob/master/libcentcli/cmd/actions/actions.go#L86) that confused me - it's very strange to see such a condition (`false` Payload and `"nil"` UID) . I understand that it has its meaning internally but just feels hacky.

**Comment by synw** [comment]
For the config the less typing/less parsing way sounds fine. I need to take some time to read the config part of the Centrifugo's code: with just a quick look it is very nice to read and well documented, I can sure learn things from it and improve my code.

About alphabetic sorting of the stats: no problem, I think I can do that.

About the user named `cli` its on purpose: would it be better to leave it empty? Or maybe provide an option to let the user decide?

For dependency vendor I must read about this before because I don't know how it works yet. Anyway if the drivers change I will just have to change the underlying wrapper so I will have no problem with that in this program.

What do you mean by client detect address scheme? I don't understand.

TLS node: this is beyond my knowledge, I can't tell actually

About the strange line: you caught me! Its a dirty hack I made that closes a routine by sending an exit signal in the main data channel : I made this to move forward on things I taught were important at the time, and in my "release early" move I totally forgot about it. I must fix this using something more idiomatic: I started to try changing it for some select/case with a close channel but can't make it to work yet. If you have any suggestion on the preferred method in such a case it is welcome: I need to improve my skills in go.
Thank you for notifying it, and for the code review.

Note: this program has an issue: when listening the incoming messages mess up with the prompt and the typing, its not as comfortable as it should be. This is due to an [issue](https://github.com/abiosoft/ishell/issues/19) in the Ishell library that I use, I guess the guy is working on it.

I am a little busy these days. As I need to take some time to study and find the idiomatic solutions and that I want to make it right and learn from it, I'll take my time and not hurry on this.

**Comment by synw** [comment]
To remove the dirty hack and close the listen channel properly I ended up using a wait group. Is this solution acceptable in an idiomatic way?
Edit: I'm not even sure this does the job correctly without memory leaks: I must work more on this anyway
Edit 2: thinking about it I think I'm totally wrong here: this is still broken.

**Comment by synw** [comment]
I made the listen function synchronous in order not to keep ugly stuff in the master. I'll search for solutions to make it asynchronous with a proper close mechanism in a branch.

Edit: I may have got it right using a close channel: is [this](https://github.com/synw/centcli/blob/async_listen/libcentcli/cmd/actions/actions.go#L79) correct?

**Comment by FZambia** [comment]
It's hard for me to say is this the best solution without looking deep in code so I can't give a proper advice yet. But at least it does not look dirty anymore. From what I see some notes:

```go
			c := make(chan bool)  // you better use  make(chan struct{}) which is more idiomatic in Go
			state.Listening[channel] = c // if you are using this channel in map in some other place you should protect access to map by mutex
			ctx.Println("Listening to channel", channel, "...")
			go func() {
				for {
					select {
					case msg := <-state.Cli.Channels: 
						if msg.Channel == channel {
							ctx.Println("->", msg.Channel, ":", msg.Payload)
						}
					case _ = <-c: // you can just do case <-c:
						return
					}
				}
			}()
```

As far as I understand it's possible to listen multiple channels, right? Maybe in this case you better do the same with only one goroutine per all listen requests that will print messages to `ctx` without filtering by channel at all.

> For dependency vendor I must read about this before because I don't know how it works yet. Anyway if the drivers change I will just have to change the underlying wrapper so I will have no problem with that in this program.

I am using `govendor` tool for this - it's not difficult, just running 

```
govendor init
govendor update +e
```

Should do the work

UPD. use `gofmt` tool to automatically fix indentations in code

**Comment by synw** [comment]
Thanks for the feedback.

> As far as I understand it's possible to listen multiple channels, right? Maybe in this case you better do the same with only one goroutine per all listen requests that will print messages to ctx without filtering by channel at all.

Yes it is possible to listen to multiple channels. One routine for all makes more sense you're right, and it simplifies the code so that's fine.

I'll continue the work and post the progress here.

**Comment by synw** [comment]
I changed it for one goroutine to listen to all channels, forgot to tag this [commit](https://github.com/synw/centcli/commit/7fd2f6fdca84af847e1b12ad8382c5596c21c764).

I can't make it right with `chan struct{}`, it seems strange to me. I left the boolean channel for now.

**Comment by synw** [comment]
About the config: I changed to use the Centrifugo terminology. I did not replace `host` and `port` by `addr` as you suggested because internally I use some data structure that needs both host and port (in the centcom lib, the drivers wrapper). I could change the underlying data structure to match with `addr` but I still wonder if that worth it

New config format:

```json
{
	"nodes": [
		{
			"name": "local",
			"host":"localhost",
			"port": 8001,
			"secret":"secret_key"
		},
		{
			"name": "local2",
			"host":"localhost",
			"port": 8002,
			"secret":"secret_key"
		}
	]
}
```

I also changed the bool channel for a struct channel as you recommended.

> Also I noticed that when listening channel you use user with ID cli - so in this moment that user will be a general user in channel and calling presence will return it in response. Unfortunately I don't know a better way - there is no concept of system users in Centrifugo...

We can give a random name to each client so they are not identified as one unique user by Centrifugo in case several clients are connected to a node: something like `cli_58535486`. It is also possible to provide a command to set the user for the current client instance: like `user cli42`. What do you think?

**Comment by FZambia** [comment]
> We can give a random name to each client so they are not identified as one unique user by Centrifugo in case several clients are connected to a node: something like cli_58535486. It is also possible to provide a command to set the user for the current client instance: like user cli42. What do you think?

I think option will be a better solution here

**Comment by synw** [comment]
At this point here is the list of what has been done (out of cleaning the dirty or clumsy stuff):

- Change config format to match Centrifugo's terminology
- Dependency vendoring
- Refactoring: use one goroutine to listen for all channels
- Flag to choose the client's username
- Alphabetic sorting of stats and humanization of the numbers

@FZambia : did I forget something?

There is still one problem remaining: [an issue with the terminal client library](https://github.com/abiosoft/ishell/issues/19) I use: the guy marked it as work in progress but it does not seem to move: it's been quite a while that I posted this issue. At this stage it is a problem as the incoming messages mess with the prompt. So if this does not move after some time I guess I will have to rewrite it without this lib. I'll wait a bit more and if nothing moves there I'll try other ways.

I don't make a release yet because of this. My plan was to stabilize everything and make a first release, then only start adding a few features like a [TermUi](https://github.com/gizak/termui) dashboard for stats if possible.

[Edit]: thinking about trying [Gocui](https://github.com/jroimartin/gocui): it can be interesting to display more information in a persistent manner, specially to get a more global view on the stats and what is happening. Maybe this lib is better for what we want here.

**Comment by FZambia** [comment]
It looks pretty cool! The only caveat I noticed is:

```
>>> chans
Available channels: []
```

Maybe better to write `Active channels` here?

**Comment by synw** [comment]
What about making a worker that can stream or distribute on requests some info taken from Centrifugo to different channels? It would separate concerns and the data could be consumed by any UI client app: browser, terminal, phone, whatever ...

It could match pretty well with my user case, I mean not only for this client app here. I am making a dashboard for [Django Instant](https://github.com/synw/django-instant) that will need some domain specific info from Centrifugo like channels activity stats, presence info and maybe more general info. 
It sounds better to aggregate these stats outside of any opiniated app and just have to listen to a stream or make requests to get them. And the "centrifugoers" could use this stats access point for free in some other apps.

I already made something like this for [Django Presence](https://github.com/synw/django-presence): a little worker that streams presence info, so that the browser clients just receive it and don't have to constantly request themselves the same info from Centrifugo, reducing the load. I had the intention to separate the Go worker and use another repository to maintain it. This could be the occasion to extend the idea to a more general purpose time based worker.

I use the Centcli mostly for quick checks and in dev. It is convenient to quickly publish a message or keep an eye on something, but not for serious monitoring. A monitoring app could benefit from a worker that can stream or serve on demand aggregated stats, taking advantage of Centrifugo's introspection capabilities.

So the idea is to make a configurable worker that will distribute info on demand or stream it. This info can be general Centrifugo stats or channels presence info. It may be extendable to aggregate and distribute more domain specific info, to be able to do like "please server watch this channel for me, collect stats about messages rates or presence info and stream them to me on that channel every x time unit".
As I have a need I will start to work on a prototype to see what can be done. 

Man, Centrifugo is definitely inspiring.

PS: for the active channels I'll correct this

[Edit]: this app could even have its own gui to display the aggregated stats, and also for its internal state management and mutability (to get an easy way to fire commands like "stop aggregating this", "start streaming that" or "start aggregating channel info for this channel with those parameters").
But this supposes an authentication mechanism over http. This way it could also serve the info over rest or graphql. The UI could also be separated from the data server for easy integration in third party apps. Lots of ideas as you see: I'll shoot a few lines of code to see what happens

**Comment by synw** [comment]
@FZambia : I made a beta release so that it is easier for people to try it out. There is just a linux binary for now. 

There is the remaining bug with the `listen` command: I will try to use something more appropriate for this feature ( [Gocui](https://github.com/jroimartin/gocui) ) to get better visualization capabilities
